[package]
name = "noise-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
rand = "0.9.2"
rodio = "0.19"
hound = "3.5.1"
rustfft = "6.4.1"
rasciichart = "0.2.17"